### ISSUE TITLE
Magnitude zero points for Roman

### ISSUE THREAD

**Issue by sepito** [spacetelescope/roman-technical-information#13]
As per request from Rob Zellem:

It would be good if you write some documentation about what exactly a zero point magnitude is. Some web pages define it as the magnitude that produces exactly one count per second, others say that in 𝑚 = −2.5 log 𝑓 + 𝐶, C is the magnitude zero point. Of course for AB magnitude the zero point is always -48.6, etc. I found this always very confusing so it would be great to have an exact definition of how the zero point magnitude for Roman is defined.

Thanks, Seppo

**Comment by tddesjardins** [comment]
Cf. #11 for related conversation.

**Comment by sepito** [comment]
Thanks @tddesjardins. So do you use the magnitude that produces exactly one count per second or the m = 2.5xlog(f) + C where C is the zero point magnitude definition (I guess these two definitions somehow amount to the same result)? So the throughputs and QEs go to the f term above? It would be good to have a detailed explanation of exactly how the magnitude zero points were defined and calculated.

**Comment by tddesjardins** [comment]
I can add the explanation, but yes, that's the intent. We do the computation to compute the flux that corresponds to one electron per second. Since the SOC L2 files will be in units of DN, we actually need to adjust to make that zeropoint correspond to one DN per second for operations, but I know all the PSO documentation so far has been in electrons and the gain is...complicated. So I can provide them for electrons -> Vega+AB+ST magnitudes / FLAM / FNU for now and then we'll make this adjustment to DN later.
